version = 0.1
[development.deploy.parameters]
stack_name = "alert-stack"
resolve_s3 = true
s3_prefix = "alert-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []