AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  alert-backend
  Cloud template for alert domain

Globals:
  Function:
    Tracing: Active
    CodeUri: ../../target/alert-backend-lambdas-1.0.0-SNAPSHOT-aws.jar
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    Runtime: java17
    Timeout: 30
    MemorySize: 1024

Resources:
  AlertApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: development
      Name: Alert API
      Description: API to expose alert services

  SetAlertsConfigurationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: SetAlertsConfigurationFunction
      Events:
        PostRequest:
          Type: Api
          Properties:
            RestApiId: !Ref AlertApi
            Path: /configuration/set
            Method: post

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Springboot sample function"
    Value: !Sub "https://${AlertApi}.execute-api.${AWS::Region}.amazonaws.com/development/configuration/set"
