AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  alert-backend
  Cloud template for alert domain

Globals:
  Function:
    Tracing: Active
    CodeUri: ../../target/alert-backend-lambdas-1.0.0-SNAPSHOT-aws.jar
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    Runtime: java17
    Timeout: 30
    MemorySize: 1024

Parameters:
  MeasurementQueueArn:
    Type: String
    Description: "ARN of the MeasurementQueue"

Resources:
  AlertApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: development
      Name: Alert API
      Description: API to expose alert services

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource:
                  - !GetAtt AlertConfigurationTable.Arn
                  - !GetAtt AlertTable.Arn
                  - !Sub "${AlertTable.Arn}/index/MineTypeIndex"
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !Ref MeasurementQueueArn

  AlertConfigurationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: alertConfigurationLambdaFunction
      Events:
        PostRequest:
          Type: Api
          Properties:
            RestApiId: !Ref AlertApi
            Path: /alert/configuration
            Method: post
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref AlertApi
            Path: /alert/configuration
            Method: get

  AlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: alertLambdaFunction
      Events:
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref AlertApi
            Path: /alert
            Method: get

  ProcessAlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: processAlertLambdaFunction
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !Ref MeasurementQueueArn
            BatchSize: 10

  AlertConfigurationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AlertConfigurationTable
      AttributeDefinitions:
        - AttributeName: mineId
          AttributeType: S
        - AttributeName: measurementType
          AttributeType: S
      KeySchema:
        - AttributeName: mineId
          KeyType: HASH
        - AttributeName: measurementType
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  AlertTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AlertTable
      AttributeDefinitions:
        - AttributeName: mineZoneId
          AttributeType: S
        - AttributeName: measurementTypeTimestamp
          AttributeType: S
        - AttributeName: mineId
          AttributeType: S
      KeySchema:
        - AttributeName: mineZoneId
          KeyType: HASH
        - AttributeName: measurementTypeTimestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: MineTypeIndex
          KeySchema:
            - AttributeName: mineId
              KeyType: HASH
            - AttributeName: measurementTypeTimestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Alert Services"
    Value: !Sub "https://${AlertApi}.execute-api.${AWS::Region}.amazonaws.com/development/configuration"
